{{- if eq .Values.cluster.provider "azure" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
parameters:
  skuName: Standard_LRS

{{- else if eq .Values.cluster.provider "aws" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: {{ .Values.storage.aws.provisioner }}
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  type: {{ .Values.storage.aws.parameters.type }}
  fsType: {{ .Values.storage.aws.parameters.fsType }}

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: {{ include "besu-node.fullname" . }}-storage
#   namespace: {{ .Release.Namespace }}
# provisioner: efs.csi.aws.com
# reclaimPolicy: Retain
# parameters:
#   provisioningMode: efs-ap
#   fileSystemId: #your_file_system_id
#   directoryPerms: "700"
#   gidRangeStart: "1000" # optional
#   gidRangeEnd: "2000" # optional
#   basePath: "/dynamic_provisioning" # optional

{{- else }}

---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: {{ include "besu-node.fullname" . }}-storage
#  namespace: {{ .Release.Namespace }}
#  labels:
#    type: local
#spec:
#  persistentVolumeReclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
#  storageClassName: {{ include "besu-node.fullname" . }}-storage
#  capacity:
#    storage: "{{ .Values.storage.sizeLimit }}"
#  accessModes:
#    - ReadWriteOnce
#    # 
#  {{- if eq .Values.storage.type "nfs" }}
#  nfs:
#    server: "{{ .Values.storage.nfs.server }}"
#    path: "/storage/{{ include "besu-node.fullname" . }}"
#  mountOptions:
#    - "{{ .Values.storage.nfs.mountOptions }}"
#  {{- else }}
#  hostPath:
#    path: "/tmp/{{ include "besu-node.fullname" . }}"
#  {{- end }}



# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: {{ include "besu-node.fullname" . }}-pvc
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "nfs-storage"
#     annotations.nfs.io/storage-path: {{ include "besu-node.fullname" . }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi

{{- end }}

